# Generated by Django 2.2.1 on 2019-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_address', models.CharField(max_length=255)),
                ('time_interval', models.IntegerField()),
                ('verify_string', models.CharField(max_length=1000)),
            ],
        ),
    ]
